# Generated by Django 3.2.18 on 2023-04-05 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_date'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts '},
        ),
    ]
